# Generated by Django 5.1.6 on 2025-02-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_pettype_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
