# Generated by Django 5.1.6 on 2025-02-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_petcategory_pettype_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='PetCategory',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
    ]
