# Generated by Django 5.1.4 on 2025-02-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
