# Generated by Django 5.1.4 on 2025-02-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Pet_Type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
    ]
