# Generated by Django 5.1.6 on 2025-03-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
    ]
