# Generated by Django 5.1.6 on 2025-03-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
