# Generated by Django 5.1.6 on 2025-03-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
