# Generated by Django 5.1.6 on 2025-03-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
