# Generated by Django 5.1.6 on 2025-03-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
